library(dplyr)
Mecha_df <- read.csv('MechaCar_mpg.csv')
head(Mecha_df)
lm(mpg ~ vehicle_length + vehicle_weight+spoiler_angle+ground_clearance+AWD, data=Mecha_df)
summary(lm(mpg ~ vehicle_length + vehicle_weight+spoiler_angle+ground_clearance+AWD, data=Mecha_df))
Suspension_df <- read.csv('Suspension_Coil.csv')
head(Suspension_df)
total_summary <- summarize(Suspension_df, Mean=mean(PSI), Median=median(PSI), 
Variance=var(PSI), SD = sd(PSI), .groups='keep')  
lot_summary <- Suspension_df %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD = sd(PSI), .groups='keep')
t.test(Suspension_df$PSI, mu=1500)
t.test(Suspension_df$PSI[Suspension_df$Manufacturing_Lot=='Lot1'], mu=1500)
t.test(Suspension_df$PSI[Suspension_df$Manufacturing_Lot=='Lot2'], mu=1500)
t.test(Suspension_df$PSI[Suspension_df$Manufacturing_Lot=='Lot3'], mu=1500) 
